### ISSUE TITLE
Code Generation based on JSON Schema

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/k8s-infra#49]
Header issue to summarize work required to make the code generator production ready. This list is incomplete and additional items should be added as they are identified.

### Features

- [x] Include the appropriate JSON schema URL in a comment on each generated type @Porges (PR: #52)
- [x] Create factory abstraction for converting from JSON schema names into Go identifiers (@theunrepentantgeek, Spec: #50, PR: #53)
- [x] Add JSON metadata for serialization into CRDs (@Porges, PR: #65 adds names)
- [x] We need to separate out generated files by service or at least schema.json name, since different services can define different types with the same name. (@Porges, PR: #63 )
- [x] Generate imports for types declared by other services (@Porges, PR: #64)
- [x] Ability to filter output by suppressing specific types/versions. (@theunrepentantgeek, PR: #60)
- [x] Extend filtering to groups (@theunrepentantgeek, PR: #78)
- [x] Handle enum properties by generating constants (@theunrepentantgeek, Discussion: #51, PR: #77)
- [ ] Define ownership model for updates/deletes 
- [ ] Support multiple versions of each service (Discussion: #57, Spec #93)

### Improvements

- [x] Sort struct members alphabetically (@theunrepentantgeek, PR: #62)
- [x] Normalize output filenames to Go conventions
- [x] Add a header to each generated file indicating it's generated code that should not be modified (@theunrepentantgeek, PR: #79)
- [x] Ensure code generation is deterministic aka same results for same inputs (@theunrepentantgeek, PR: #75)
- [ ] Add `--verbose` or `--debug` option and make normal execution quieter (@theunrepentantgeek)
- [ ] Use a specific naming convention to allow generated files to be separated from hand coded files
- [x] Handle AnyOf/OneOf better (@matthchr, discussion at #71, OneOf PR #98)
- [x] Dedupe duplicated types in AnyOf/OneOf/AllOf (@matthchr in #98 for OneOf, also working on it for others as well)
- [ ] Consider using [go-cmp](https://github.com/google/go-cmp) to simplify implementation of Equals (@theunrepentantgeek)
- [ ] Handle `apiVersion` property specially
- [ ] Mark a `storageVersion`
- [ ] Enums need a kubebuilder validation comment

### TODOs
- [ ] Figure out how best to read the full package path (see: https://github.com/Azure/k8s-infra/pull/64#discussion_r420407254)

Each item should include a `#ref` to another issue with more detail, if required. 
When someone starts working on an issue, please `@ref` them on that issue for coordination.

**Comment by matthchr** [comment]
Closing this in favor of the project at https://github.com/Azure/k8s-infra/projects/2 which I have added all of the remaining open items to
